#!/usr/bin/env python3
"""
Build dist/index.html listing all rendered reports.

Usage: python scripts/render_index.py
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
DIST_DIR = ROOT / "dist"


def build_card(slug: str, data: dict) -> str:
    meta = data.get("meta", {})
    verdict = data.get("verdict", {})
    counts = verdict.get("evidence_counts", {})
    status_label = {
        "real":         ("✓ 真实需求",   "#5b7a52", "#f1f6ee"),
        "partial":      ("◐ 部分支持",   "#a0533c", "#faf0eb"),
        "insufficient": ("⚠ 证据不足",   "#a0533c", "#f7e9e3"),
    }.get(verdict.get("status", "partial"), ("◐", "#737277", "#f5f1e7"))
    pill_text, pill_color, pill_bg = status_label

    return f'''
    <a class="card" href="./{slug}.html">
      <div class="card-head">
        <div class="card-mode">{meta.get("mode", "")}</div>
        <div class="card-pill" style="color:{pill_color};background:{pill_bg};border-color:{pill_color}">{pill_text}</div>
      </div>
      <h2>{meta.get("idea", slug)}</h2>
      <p class="card-thesis">{meta.get("thesis", "")}</p>
      <div class="card-counts">
        <span>raw <b>{counts.get("raw_voices", 0)}</b></span>
        <span>mkt <b>{counts.get("marketplace", 0)}</b></span>
        <span>ed <b>{counts.get("editorials", 0)}</b></span>
        <span>players <b>{len(data.get("players", []))}</b></span>
      </div>
      <div class="card-foot">{meta.get("target_market", "")} · {meta.get("timestamp", "")}</div>
    </a>'''


def main() -> int:
    DIST_DIR.mkdir(exist_ok=True)
    files = sorted(DATA_DIR.glob("*.json"))
    cards = []
    for f in files:
        try:
            d = json.loads(f.read_text(encoding="utf-8"))
            cards.append(build_card(f.stem, d))
        except Exception as e:
            print(f"⚠ skipping {f.name}: {e}")

    html = f'''<!doctype html>
<html lang="zh"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>VIBE Category Research · Index</title>
<style>
  :root{{
    --bg:#faf8f4; --ink:#1c1d20; --ink-2:#3d3e44; --ink-3:#737277; --line:#e3ddcf;
    --mono:'SF Mono',Menlo,Monaco,monospace; --serif:'Iowan Old Style',Cambria,serif;
  }}
  *{{box-sizing:border-box}}
  html,body{{margin:0;padding:0;background:var(--bg);color:var(--ink);font-family:-apple-system,system-ui,sans-serif}}
  header{{padding:50px 24px 24px;border-bottom:1px solid var(--line);max-width:920px;margin:0 auto}}
  header .brand{{font-family:var(--mono);font-size:11px;letter-spacing:.18em;color:var(--ink-3);text-transform:uppercase}}
  header h1{{font-family:var(--serif);font-size:30px;font-weight:600;margin:8px 0 6px;letter-spacing:-.01em}}
  header p{{font-family:var(--serif);font-style:italic;color:var(--ink-2);margin:0;font-size:15px}}
  main{{max-width:920px;margin:0 auto;padding:24px;display:grid;grid-template-columns:repeat(auto-fill,minmax(380px,1fr));gap:18px}}
  .card{{display:block;border:1px solid var(--line);background:#fff;border-radius:8px;padding:22px 24px;text-decoration:none;color:inherit;transition:transform .15s ease, box-shadow .15s ease}}
  .card:hover{{transform:translateY(-2px);box-shadow:0 6px 18px rgba(28,29,32,.07)}}
  .card-head{{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}}
  .card-mode{{font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;color:var(--ink-3);text-transform:uppercase}}
  .card-pill{{font-family:var(--mono);font-size:10px;letter-spacing:.06em;text-transform:uppercase;padding:3px 10px;border-radius:11px;border:1px solid}}
  .card h2{{font-family:var(--serif);font-size:20px;font-weight:600;margin:0 0 8px;letter-spacing:-.01em}}
  .card-thesis{{font-family:var(--serif);font-size:14px;color:var(--ink-2);line-height:1.55;margin:0 0 14px;font-style:italic}}
  .card-counts{{display:flex;gap:14px;font-family:var(--mono);font-size:10.5px;color:var(--ink-3);margin-bottom:8px}}
  .card-counts b{{color:var(--ink);font-weight:600;margin-left:3px}}
  .card-foot{{font-family:var(--mono);font-size:10px;color:var(--ink-3);letter-spacing:.06em;border-top:1px solid var(--line);padding-top:10px;text-transform:uppercase}}
  footer{{max-width:920px;margin:0 auto;padding:24px;font-family:var(--mono);font-size:11px;color:var(--ink-3);letter-spacing:.04em;border-top:1px solid var(--line)}}
</style>
</head><body>

<header>
  <div class="brand">VIBE · CATEGORY DEEP DIVE</div>
  <h1>Category Research Reports</h1>
  <p>Evidence-based research on whether a product demand is real. {len(files)} report{'s' if len(files) != 1 else ''} · built {date.today().isoformat()}.</p>
</header>

<main>
  {''.join(cards)}
</main>

<footer>
  Generated by <code>scripts/render_index.py</code> from <code>data/*.json</code>. Re-run any time with <code>make all</code>.
</footer>

</body></html>'''

    out = DIST_DIR / "index.html"
    out.write_text(html, encoding="utf-8")
    print(f"✓ {out.relative_to(ROOT)}  ({len(cards)} cards)")

    # Copy assets the chat-user viewer needs:
    #  - the report template (viewer fetches it + injects pasted JSON)
    #  - the data JSONs (so viewer's "load sample" + ?data= work on Pages)
    import shutil
    tpl_src = ROOT / "templates" / "lens-report-template.html"
    if tpl_src.exists():
        shutil.copy(tpl_src, DIST_DIR / "_template.html")
        print("✓ dist/_template.html (for viewer.html)")
    for f in DATA_DIR.glob("*.json"):
        shutil.copy(f, DIST_DIR / f.name)
    print(f"✓ copied {len(list(DATA_DIR.glob('*.json')))} data files to dist/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
